CREATE TABLESPACE TBS_DATA DATAFILE 'C:\Databases\Oracle19c\oradata\BDPIZZA\DATAFILES\BDPIZZA_Data01.DBF' SIZE 1G DEFAULT STORAGE (INITIAL 5M NEXT 5M PCTINCREASE 0);
CREATE TABLESPACE TBS_INDEX DATAFILE 'C:\Databases\Oracle19c\oradata\BDPIZZA\DATAFILES\BDPIZZA_Index01.DBF' SIZE 100M DEFAULT STORAGE (INITIAL 5M NEXT 5M PCTINCREASE 0);


alter session set "_ORACLE_SCRIPT" = TRUE;
CREATE USER ADMPIZZA IDENTIFIED BY Admin01 DEFAULT TABLESPACE TBS_DATA TEMPORARY TABLESPACE TEMP;
ALTER USER ADMPIZZA IDENTIFIED BY Admin01 DEFAULT TABLESPACE TBS_INDEX;
GRANT CONNECT TO ADMPIZZA;
GRANT RESOURCE TO ADMPIZZA;
ALTER USER ADMPIZZA QUOTA UNLIMITED ON TBS_DATA;
ALTER USER ADMPIZZA QUOTA UNLIMITED ON TBS_INDEX;
GRANT DBA TO ADMPIZZA;


CREATE TABLE TB_ROLES(
   TBR_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TBR_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
   TBR_NOMBRE VARCHAR2(50) NOT NULL
) TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_USUARIOS(
   TBU_ID INTEGER NOT NULL CONSTRAINT PK_TBU_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
   TBU_NOMBRE VARCHAR2(50) NOT NULL,
   TBU_APELLIDO1 VARCHAR2(50) NOT NULL,
   TBU_APELLIDO2 VARCHAR2(50) NOT NULL,
   TBU_DIRRECION VARCHAR2(200) NOT NULL,
   TBU_TELEFONO NUMBER NOT NULL,
   TBR_ID INTEGER NOT NULL,
   CONSTRAINT PK_TBR_ID_TBU FOREIGN KEY (TBR_ID) REFERENCES TB_ROLES(TBR_ID)
) TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_FACTURAS(
   TBF_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TBF_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
   TBF_FECHA DATE NOT NULL,
   TBF_TOTAL FLOAT NOT NULL,
   TBU_ID INTEGER NOT NULL,
   CONSTRAINT PK_TBU_ID_TBF FOREIGN KEY (TBU_ID) REFERENCES TB_USUARIOS(TBU_ID)
) TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_TIPO_PRODUCTO(
   TBTP_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TBTP_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
   TBTP_NOMBRE VARCHAR2(50) NOT NULL
) TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_PRODUCTOS(
   TBP_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TBP_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
   TBP_NOMBRE VARCHAR2(50) NOT NULL,
   TBP_DESCRIPCION VARCHAR2(200) NOT NULL,
   TBP_PRECIO FLOAT NOT NULL,
   TBTP_ID INTEGER NOT NULL,
   CONSTRAINT PK_TBTP_ID_BDP FOREIGN KEY (TBTP_ID) REFERENCES TB_TIPO_PRODUCTO(TBTP_ID)
) TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_PROMOCIONES(
   TBPR_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TBPR_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
   TBPR_DESCRIPCION VARCHAR2(200) NOT NULL,
   TPPR_ESTDO CHAR(1) NOT NULL
) TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_PROMOCIONES_PRODUCTOS(
   TBPR_ID INTEGER GENERATED ALWAYS AS IDENTITY,
   TBP_ID INTEGER NOT NULL,
   CONSTRAINT PK_TBPR_ID_TBPP FOREIGN KEY (TBPR_ID) REFERENCES TB_PROMOCIONES(TBPR_ID),
   CONSTRAINT PK_TBP_ID_TBPP FOREIGN KEY (TBP_ID) REFERENCES TB_PRODUCTOS(TBP_ID)
) TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_SUCURSALES(
    TBS_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TBS_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
    TBS_NOMBRE VARCHAR2(50) NOT NULL
)TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_PEDIDOS(
   TBPE_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TBPE_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
   TBPE_ENVIO CHAR(1) NOT NULL,
   TBF_ID INTEGER NOT NULL,
   TBS_ID INTEGER NOT NULL,
   CONSTRAINT PK_TBF_ID_TBPE FOREIGN KEY (TBF_ID) REFERENCES TB_FACTURAS(TBF_ID),
   CONSTRAINT PK_TBF_TBS_ID FOREIGN KEY (TBS_ID) REFERENCES TB_SUCURSALES(TBS_ID)
) TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_DETALLE_FACTURA(
   TBDF_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TBDF_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
   TBDF_CANTIDAD CHAR(1) NOT NULL,
   TBF_ID INTEGER NOT NULL,
   TBP_ID INTEGER NOT NULL,
   CONSTRAINT PK_TBF_ID_TBPDF FOREIGN KEY (TBF_ID) REFERENCES TB_FACTURAS(TBF_ID),
   CONSTRAINT PK_TBP_ID_TBPDF FOREIGN KEY (TBP_ID) REFERENCES TB_PRODUCTOS(TBP_ID)
) TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

CREATE TABLE TB_LOGIN(
    TBL_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TBL_ID PRIMARY KEY USING INDEX TABLESPACE TBS_INDEX,
    TBL_NOMBRE VARCHAR2(50) NOT NULL,
    TBU_ID INTEGER NOT NULL,
    CONSTRAINT PK_TBL_TBU_ID FOREIGN KEY (TBU_ID) REFERENCES TB_USUARIOS(TBU_ID)
)TABLESPACE TBS_DATA STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);
